// lib/productsData.js
export const productsData = {
  "luxurious-elixir-rough": {
    name: "Luxurious Elixir Rough",
    price: "220.00",
    rating: 4,
    reviews: 88,
    description: "A bold and captivating fragrance with rough edges of luxury, designed for those who dare to stand out.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "the-golden-legacy": {
    name: "The Golden Legacy",
    price: "160.00",
    rating: 4,
    reviews: 170,
    description: "A timeless classic that weaves a golden thread through every moment, leaving a lasting legacy of elegance.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "luxurious-elixir": {
    name: "Luxurious Elixir",
    price: "250.00",
    rating: 5,
    reviews: 80,
    description: "Step into a world of unparalleled opulence with Luxurious Elixir, an exquisite fragrance that weaves an enchanting symphony of gold and luxury.",
    variants: [
      { id: 1, volume: "100 ml" },
      { id: 2, volume: "150 ml" },
    ],
  },
  "luxurious-essence": {
    name: "Luxurious Essence",
    price: "260.00",
    rating: 3,
    reviews: 121,
    description: "The pure essence of luxury distilled into a single unforgettable fragrance experience.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "aurum-aura": {
    name: "Aurum Aura",
    price: "200.00",
    rating: 4,
    reviews: 195,
    description: "A radiant golden aura that surrounds you with warmth, confidence, and an air of sophistication.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "gleaming-gilt": {
    name: "Gleaming Gilt",
    price: "160.00",
    rating: 4,
    reviews: 115,
    description: "Gleaming with golden brilliance, this fragrance captures the shimmer of precious metals in every spritz.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "gilded-elixir-rough": {
    name: "Gilded Elixir Rough",
    price: "170.00",
    rating: 4,
    reviews: 88,
    description: "Where raw power meets gilded refinement — a fragrance for those who wear their strength with grace.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "golden-luminary": {
    name: "Golden Luminary",
    price: "120.00",
    rating: 4,
    reviews: 190,
    description: "Illuminate every room you enter with this luminous golden scent that radiates warmth and light.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "decadent-opal": {
    name: "Decadent Opal",
    price: "160.00",
    rating: 5,
    reviews: 48,
    description: "An opulent opalescent fragrance that shifts and shimmers, revealing new facets with every wear.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "gilded-elixir": {
    name: "Gilded Elixir",
    price: "200.00",
    rating: 5,
    reviews: 19,
    description: "Pure gold in a bottle — a deeply refined elixir that transforms the ordinary into the extraordinary.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "glamourous-gilt": {
    name: "Glamourous Gilt",
    price: "160.00",
    rating: 4,
    reviews: 121,
    description: "Dripping in glamour and gilded in gold, this fragrance is for those who live life in full sparkle.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "luxury-enigma": {
    name: "Luxury Enigma",
    price: "190.00",
    rating: 5,
    reviews: 102,
    description: "A mysterious and enigmatic blend that keeps people guessing — the ultimate luxury in ambiguity.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "velyscent-noir": {
    name: "Velyscent Noir",
    price: "290.00",
    rating: 4,
    reviews: 65,
    description: "Dark, intense, and irresistibly mysterious — Noir is the shadow that follows you everywhere.",
    variants: [{ id: 1, volume: "100 ml" }],
  },
  "royal-oud": {
    name: "Royal Oud",
    price: "310.00",
    rating: 5,
    reviews: 43,
    description: "The king of fragrances — rich, smoky oud layered with royal spices fit for those of distinguished taste.",
    variants: [
      { id: 1, volume: "100 ml" },
      { id: 2, volume: "150 ml" },
    ],
  },
};